[features]
seeds = false
skip-lint = false
[programs.localnet]
increment_pda = "GAkGNP1PCT88mXeC3cmXdi9FUtSNAH3sm5FW9QaxSeNo"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/bamdad/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
